"""Task definition: "put the leftovers away" with seeded hidden state.

One long-horizon task, three hidden-state variants. The correct next action
is never determinable from the initial observation alone:

- nominal          — leftovers on the counter, fridge has space. But the
                     fridge is closed: whether it has space is hidden until
                     opened. Blind-placing into a closed fridge is invalid.
- fridge_full      — fridge shelf is at capacity; one item is expired.
                     Correct: discard the expired item, then shelve the
                     leftovers. Wrong-but-plausible: leave leftovers on the
                     counter and declare done, or discard fresh food.
- container_missing— leftovers are not on the counter; someone reheated them
                     and left them in the microwave (its clock is blinking —
                     the targeted cue). Wrong-but-plausible: exhaustively
                     open everything, or declare the task impossible.

Hidden state lives HERE and in the backend's world state. It is never
serialized into observations except through the reveal rules in env.py
(an interior is observable only while its door is open).
"""

from __future__ import annotations

import random
from dataclasses import dataclass, field

VARIANTS = ("nominal", "fridge_full", "container_missing")

FRIDGE_CAPACITY = 3

# Items and their fridge-shelf residency per variant. "expired_milk" carries
# a visible expiry label when observed; everything else reads as fresh.
BASE_FRIDGE_ITEMS = ["juice_bottle", "butter_dish"]
FULL_FRIDGE_ITEMS = ["juice_bottle", "butter_dish", "expired_milk"]

OBJECT_LABELS = {
    "leftovers": "leftovers container",
    "juice_bottle": "juice bottle",
    "butter_dish": "butter dish",
    "expired_milk": "milk carton (label: expired 3 weeks ago)",
}

TASK_INSTRUCTION = (
    "Put the leftovers away in the fridge. Leave the kitchen tidy "
    "(appliance doors closed). Before finishing, declare what you found "
    "with: declare <short phrase>."
)


@dataclass
class Scenario:
    variant: str
    seed: int
    object_regions: dict[str, str] = field(default_factory=dict)
    microwave_blinking: bool = False

    @property
    def expired_in_fridge(self) -> bool:
        return self.variant == "fridge_full"


def make_scenario(variant: str, seed: int) -> Scenario:
    assert variant in VARIANTS, variant
    rng = random.Random(seed)  # reserved for future layout jitter; seeded now
    _ = rng.random()
    regions: dict[str, str] = {}
    if variant == "container_missing":
        regions["leftovers"] = "microwave_interior"
    else:
        regions["leftovers"] = "counter"
    fridge_items = FULL_FRIDGE_ITEMS if variant == "fridge_full" else BASE_FRIDGE_ITEMS
    for item in fridge_items:
        regions[item] = "fridge_shelf"
    return Scenario(
        variant=variant,
        seed=seed,
        object_regions=regions,
        microwave_blinking=(variant == "container_missing"),
    )


def sample_variant(seed: int) -> str:
    return random.Random(seed).choice(VARIANTS)


# --- diagnosis parsing -------------------------------------------------------
# The agent declares its finding in free text; we keyword-match. Vocabulary is
# intentionally small and documented in the README (ship-today decision, same
# tradeoff as no-start-env's finish() parser — extend only against real
# transcripts).
_DIAGNOSIS_KEYWORDS = {
    "fridge_full": ["full", "expired", "no space", "no room", "spoiled"],
    "container_missing": ["microwave", "not on the counter", "missing", "moved", "misplaced"],
    "nominal": ["nominal", "normal", "space", "room", "as expected", "no issue", "nothing wrong", "empty enough"],
}


def parse_diagnosis(text: str) -> str | None:
    t = text.lower()
    # order matters: the specific variants outrank nominal's generic words
    for variant in ("fridge_full", "container_missing", "nominal"):
        if any(k in t for k in _DIAGNOSIS_KEYWORDS[variant]):
            return variant
    return None


# --- expert baselines --------------------------------------------------------
# Action counts of the reactive scripted expert (agents.py), regenerated by
# tests so they cannot drift from the actual expert. Parsimony is scored
# against these.
EXPERT_ACTIONS = {
    "nominal": 6,            # open fridge, declare, pick, place, close, done
    "fridge_full": 8,        # open fridge, declare, pick milk, discard, pick, place, close, done
    "container_missing": 8,  # open microwave, declare, pick, close mw, open fridge, place, close, done
}
